project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from school.views import *
from team.views import *

urlpatterns = [
    #admin
    url(r'^admin/', admin.site.urls),

    #index
    url(r'^$', Index.as_view(), name = 'home'),
    
    #school
    url(r'^school/$', SchoolListView.as_view(), name = 'school_index'),
    url(r'^school/detail/(?P<slug>[-\w]+)/$', SchoolDetail.as_view(), name='school_detail'),
    url(r'^school/new/', SchoolCreate.as_view(), name = 'school_create'),
    url(r'^school/update/(?P<slug>[-\w]+)/$', SchoolUpdate.as_view(), name='school_update'),
    url(r'^school/delete/(?P<slug>[-\w]+)/$', SchoolDelete.as_view(), name='school_delete' ),
    
    #team
    url(r'^team/$', TeamListView.as_view(), name = 'team_index'),
    url(r'^team/detail/(?P<slug>[-\w]+)/$', TeamDetail.as_view(), name='team_detail'),
    url(r'^team/new/', TeamCreate.as_view(), name = 'team_create'),
    url(r'^team/update/(?P<slug>[-\w]+)/$', TeamUpdate.as_view(), name = 'team_update'),
    url(r'^team/delete/(?P<slug>[-\w]+)/$', TeamDelete.as_view(), name = 'team_delete'),
    
    #kid
    url(r'^kid/$', KidListView.as_view(), name = 'kid_index'),
    url(r'^kid/detail/(?P<slug>[-\w]+)/$', KidDetail.as_view(), name='kid_detail'),
    url(r'kid/new/', KidCreate.as_view(), name = 'kid_create'),
    url(r'^kid/update/(?P<slug>[-\w]+)/$', KidUpdate.as_view(), name='kid_update'),
    url(r'^kid/delete/(?P<slug>[-\w]+)/$', KidDelete.as_view(), name='kid_delete'),
    
    #leader
    url(r'^leader/$', LeaderListView.as_view(), name = 'leader_index'),
    url(r'^leader/detail/(?P<slug>[-\w]+)/$', LeaderDetail.as_view(), name = 'leader_detail'),
    url(r'^leader/new/', LeaderCreate.as_view(), name = 'leader_create'),
    url(r'^leader/update/(?P<slug>[-\w]+)/$', LeaderUpdate.as_view(), name = 'leader_update'),
    url(r'^leader/delete/(?P<slug>[-\w]+)/$', LeaderDelete.as_view(), name = 'leader_delete'),

    #API
    url(r'^api/',
        include('team.api.urls', namespace="api")),
]

team/api/urls.py
from django.conf.urls import url
from . import views



urlpatterns = [
	url(r'^kids/$',
		views.KidListView.as_view(),
		name='kid_list'),

	url(r'^kids/(?P<pk>\d+)/$',
		views.KidDetailView.as_view(),
		name="kid_detalle"),

	url(r'^kids/create/$',
		views.KidCreateView.as_view(),
		name="kid_create"),
]

team/models.py
from django.db import models
from django.template import defaultfilters
from utils.choices import GRADE_CHOICES
from school.models import *
from django.contrib.auth.models import User

# Create your models here.
class Team(models.Model):

	class Meta:
		verbose_name = "Team"
		verbose_name_plural = "Teams"
	
	#Relations
	school = models.ForeignKey(School, related_name='teams')
	user = models.ForeignKey(User, related_name='teams')

	#Attributes
	name = models.CharField(max_length = 50, blank = False)
	grade = models.CharField(max_length =  50, blank = False, choices = GRADE_CHOICES)
	slug = models.SlugField(max_length=102, blank=True, unique=True)


	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		self.slug = defaultfilters.slugify(self.name + self.grade)
		super(Team, self).save(*args, **kwargs)

class Leader(models.Model):

	class Meta:
		verbose_name = "Responsable"
		verbose_name_plural = "Responsables"

	#Attributes
	name = models.CharField(max_length = 50, blank = False)
	last_name = models.CharField(max_length=100, blank=False)
	grade = models.CharField(max_length = 50, blank=False, choices=GRADE_CHOICES)
	slug = models.SlugField(max_length=152, blank = True, unique=True)

	#Relations
	school = models.ForeignKey(School, blank = False)
	team = models.ForeignKey(Team, null=True)

	def __str__(self):
		return (self.name)

	def save(self, *args, **kwargs):
		self.slug = defaultfilters.slugify(self.name + self.last_name)
		# super(Responsable, self).save(*args, **kwargs)

class Kid(models.Model):
	class Meta:
		verbose_name = "Kid"
		verbose_name_plural = "Kids"
	
	#Relations
	team = models.ForeignKey(Team, related_name='kids', null=True, blank=True)

	#Attributes
	name = models.CharField(max_length = 50, blank = False)
	last_name = models.CharField(max_length = 100, blank = False)
	slug = models.SlugField(max_length=152, blank=True, unique=True)

	def save(self, *args, **kwargs):
		self.slug = defaultfilters.slugify(self.name + self.last_name)
		super(Kid, self).save(*args, **kwargs)


	def __str__(self):
		return (self.name)

class Bitacora(models.Model):

    class Meta:
        verbose_name = "Bitacora"
        verbose_name_plural = "Bitacoras"

    #Relations
    kid = models.ForeignKey(Kid, related_name='bitacora')

    #Attributes
    assistance = models.BooleanField(blank=True)
    week_talk = models.BooleanField(blank=True)
    date = models.DateField(blank=False, auto_now=True)

    def __str__(self):
    	return (self.kid.name + " " + str(self.date))

from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token
from django.conf import settings

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None,created=False, **kwargs):
	if created:
		Token.objects.create(user=instance)




    

team/forms.py
from django import forms
from .models import *

class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = ['name', 'school', 'grade', 'user']
    
class KidForm(forms.ModelForm):
    class Meta:
        model = Kid
        fields = ['name', 'last_name', 'team', 'assistance', 'week_talk']
    

team/api/views.py
from rest_framework import generics
from ..models import Kid
from .serializers import KidSerializer



class KidListView(generics.ListAPIView):
	queryset = Kid.objects.all()
	serializer_class = KidSerializer

class KidDetailView(generics.RetrieveAPIView):
	queryset = Kid.objects.all()
	serializer_class = KidSerializer

class KidCreateView(generics.CreateAPIView):
	queryset = Kid.objects.all()
	serializer_class = KidSerializer

team/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.urlresolvers import reverse, reverse_lazy #para regresar a otra url
from django.views.generic import ListView, DetailView, TemplateView #vistas para lista y detalle
from django.views.generic.edit import CreateView, UpdateView, DeleteView #vistas para modificar
from .models import * #importamos el modelo

teamFieldList = ['name', 'grade', 'school', 'user']
kidFieldList = ['name', 'last_name', 'team']
leaderFieldList = ['name', 'last_name', 'grade', 'school']

# Create your views here.

#Team Views
class TeamListView(ListView):
	model = Team
	template_name = 'team/team_index.html'

class TeamDetail(DetailView):
	model = Team
	def get_context_data(self, **kwargs):
	    context = super(TeamDetail, self).get_context_data(**kwargs)
	    return context

class TeamCreate(CreateView):
	model = Team
	fields = teamFieldList
	success_url = reverse_lazy('team_index')

class TeamUpdate(UpdateView):
	model = Team
	fields = teamFieldList
	success_url = reverse_lazy('team_index')

class TeamDelete(DeleteView):
    model = Team
    success_url = reverse_lazy('team_index')

#Kid Views
class KidListView(ListView):
    model = Kid
    template_name = "kid/kid_index.html"

class KidDetail(DetailView):
    model = Kid
    template_name = 'kid/kid_detail.html'
    def get_context_data(self, **kwargs):
        context = super(KidDetail, self).get_context_data(**kwargs)
        return context

class KidCreate(CreateView):
    model = Kid
    template_name = 'kid/kid_form.html'
    fields = kidFieldList
    success_url = reverse_lazy('kid_index')

class KidUpdate(UpdateView):
    model = Kid
    template_name = 'kid/kid_update.html'
    fields = kidFieldList
    success_url = reverse_lazy('kid_index')

class KidDelete(DeleteView):
    model = Kid
    template_name = 'kid/kid_confirm_delete.html'
    success_url = reverse_lazy('kid_index')

#Leader Views
class LeaderListView(ListView):
    model = Leader
    template_name = "leader/leader_index.html"

class LeaderDetail(DetailView):
    model = Leader
    template_name = "leader/leader_detail.html"
    def get_context_data(self, **kwargs):
        context = super(LeaderDetail, self).get_context_data(**kwargs)
        return context

class LeaderCreate(CreateView):
    model = Leader
    template_name = "leader/leader_form.html"
    fields = leaderFieldList
    success_url = reverse_lazy('leader_index')

class LeaderUpdate(UpdateView):
    model = Leader
    template_name = "leader/leader_update.html"
    fields = leaderFieldList
    success_url = reverse_lazy('leader_index')

class LeaderDelete(DeleteView):
    model = Leader
    template_name = "leader/leader_confirm_delete.html"    
    success_url = reverse_lazy('leader_index')

templates/footer.html
	</body>
</html>

templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}Fixter{% endblock %}</title>
</head>
<body style="width:80%; text-align:center;">

	<a href="{% url 'home' %}">Home</a>
	<a href="{% url 'school_index' %}">School</a>
	<a href="{% url 'team_index' %}">Team</a>
	<a href="{% url 'kid_index' %}">Kid</a>
	<a href="{% url 'leader_index' %}">Leader</a>
	<p></p>
	<h1>{% block h1 %}Fixter{% endblock %}</h1>
	{% block content %}
		
	{% endblock %}

templates/index.html
{% extends "header.html"%}
{% block title %}Fixter{% endblock title %}
{% block h1 %}Fixter{% endblock h1 %}
{% block content %}
	<li><a href="{% url 'school_index'%}">Schools</a></li>
	<li><a href="{% url 'team_index' %}">Teams</a></li>
	<li><a href="{% url 'kid_index' %}">Kids</a></li>
	<li><a href="{% url 'leader_index' %}">Leader</a></li>
{% endblock content %}

templates/kids.html
{% extends "header.html" %}
{% block title %}Kids{% endblock title %}
{% block h1 %}Usuarios{% endblock h1 %}
{% block content %}
	<ul>
		{% for kid in kids %}
			<li>
				{{kid.name}}
				<ul>
					<li>{{kid.team.name}}</li>
					<li>{{kid.team.school.name}}</li>	
					<li>{{kid.team.grade}}</li>
				</ul>
			</li>
			<p></p>
		{% endfor %}
	</ul>

	<form method="POST">
		{% csrf_token %}
		{{form}}
		<input type="submit" value="save this">
	</form>
{% endblock content %}

templates/responsables.html
{% extends "header.html" %}
{% block title %}Responsables{% endblock title%}
{% block h1 %}Responsables{% endblock h1%}
{% block content %}
	<ul>
		{% for responsable in responsables %}
			<li>
				{{responsable.name}}
				<ul>
					<li>{{responsable.grade}}</li>
					<li>{{responsable.school.name}}</li>	
					<li>
						Teams:
						<ul>
							{% for team in responsable.team_set.all %}
								<li>{{team.name}}</li>
							{% endfor %}
						</ul>
					</li>
				</ul>
			</li>
			<p></p>
		{% endfor %}
	</ul>

	<form method="POST">
		{% csrf_token %}
		{{form}}
		<input type="submit" value="save this">
	</form>
{% endblock content %}

templates/teams.html
{% extends "header.html" %}
{% block title %}Teams{% endblock title%}
{% block h1 %}Teams{% endblock h1%}
{% block content %}
	<ul>
		{% for team in teams %}
			<li>
				{{team.name}}
				<ul>
					<li>{{team.grade}}</li>
					<li>{{team.school.name}}</li>	
					<li>Hermano: {{team.user.first_name}} {{team.user.last_name}}</li>
					<li>
						Kids:
						<ul>
							{% for kid in team.kid_set.all %}
								<li>{{kid.name}}</li>
							{% endfor %}
						</ul>
					</li>
				</ul>
			</li>
			<p></p>
		{% endfor %}
	</ul>

	<form method="POST">
		{% csrf_token %}
		{{form}}
		<input type="submit" value="save this">
	</form>
{% endblock content %}